### ISSUE TITLE
Wrong perception of dict config

### ISSUE THREAD

**Issue by truong-le-terralogic** [DennisPhamPro/demo-logging#1]
Please use dictionary for configuration for logging.
Do not use yaml config.
Source: https://docs.python.org/3/library/logging.config.html

Example:
{
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console' : {
            'format': '{asctime}: {levelname}: {message} ',
            'style': '{',
            'datefmt': '%Y/%m/%d %H:%M:%S'
        },
        'file': {
            'format': '{asctime}: {levelname}: at line no {lineno}: {message} ',
            'style': '{',
            'datefmt': '%Y/%m/%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'class': 'logging.FileHandler',
            'formatter': 'file',
            'filename': log_f_path,
            'mode': 'a',
            'encoding': 'utf8'
        }
    },
    # 'root': {
    #     'handlers': ['console'],
    #     'level': config('DJANGO_LOG_LEVEL', default = 'INFO', cast=str),
    # },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': config('DJANGO_LOG_LEVEL', default = 'INFO', cast=str),
            'propagate': True,
        },
        'django.*': {
            'handlers': ['console', 'file'],
            'level': config('DJANGO_LOG_LEVEL', default = 'INFO', cast=str),
            'propagate': True,
        },
        'custom': {
            'handlers': ['console', 'file'],
            'level': config('DJANGO_LOG_LEVEL', default = 'INFO', cast=str),
            'propagate': True,
        }
    },
}

- Requirements:
   - datetime formatter for logging
   - a logger can log 2 areas: console + file
   - file mode: "r" or "w". Which one to choose and how are differences between them?
   - main handlers: StreamHandler & FileHandler
   - dict config shall have:
      1.  formatters
      2. filters
      3. handlers
      4. loggers
      5. root
   - What does "propagate" mean?
   - what does "incremental" mean?
   - How to wite logs to 2 files:
      * 1 file to contain logs at level INFO
      * 1 files to contain logs at level DEBUG

**Comment by DennisPhamPro** [comment]
viết config vào thẳng 1 biến dict luôn đúng không anh trai? Không sử dụng yaml hay json gì hết nhỉ?
`log_config = {
    "version":1,
    "root":{
        "handlers" : ["console"],
        "level": "DEBUG"
    },
    "handlers":{
        "console":{
            "formatter": "std_out",
            "class": "logging.StreamHandler",
            "level": "DEBUG"
        }
    },
    "formatters":{
        "std_out": {
            "format": "%(asctime)s : %(levelname)s : %(module)s : %(funcName)s : %(lineno)d : (Process Details : (%(process)d, %(processName)s), Thread Details : (%(thread)d, %(threadName)s))\nLog : %(message)s",
            "datefmt":"%d-%m-%Y %I:%M:%S(%p)S"
        }
    },
}`
like this?

**Comment by truong-le-terralogic** [comment]
uhm. Chỉ sử sụng dictionary
